name: Auto Merge Exercism PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Automerge PR
        id: automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report result
        run: |
          if [[ "${{ steps.automerge.outputs.mergeResult }}" == "merged" ]]; then
            echo "✅ Success: Exercism PR was merged."
          elif [[ "${{ steps.automerge.outputs.mergeResult }}" == "already-merged" ]]; then
            echo "ℹ️ Info: Exercism PR was already merged."
          else
            echo "❌ Error: Exercism PR could not be merged. Reason: ${{ steps.automerge.outputs.mergeResult }}"
          fi
